import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, OneToMany, CreateDateColumn } from 'typeorm';
import { Branch } from './Branch';
import { User } from './User';
import { Customer } from './Customer';

@Entity('sales')
export class Sale {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ unique: true })
  receiptNumber!: string;

  @ManyToOne(() => Branch, (branch) => branch.sales)
  branch!: Branch;

  @ManyToOne(() => User)
  cashier!: User;

  @ManyToOne(() => Customer, { nullable: true })
  customer?: Customer;

  // Snapshot of customer name for historical accuracy
  @Column({ nullable: true })
  customerName?: string;

  @Column('decimal', { precision: 10, scale: 2 })
  totalAmount!: number;

  @Column('decimal', { precision: 10, scale: 2 })
  taxAmount!: number; // VAT 16%

  @Column('decimal', { precision: 10, scale: 2 })
  netAmount!: number; // Amount before tax

  @Column({ default: 'CASH' })
  paymentMethod!: string; 

  @Column({ type: 'json', nullable: true })
  paymentDetails?: any;

  @Column({ type: 'json' })
  itemsSnapshot!: any[]; 

  // --- KRA eTIMS Fields ---
  @Column({ nullable: true })
  kraControlCode?: string; // The Invoice Number generated by KRA

  @Column({ nullable: true })
  kraQrCodeUrl?: string; // URL to verify on iTax

  @Column({ nullable: true })
  kraSignature?: string; // Digital signature

  @Column({ nullable: true })
  kraDate?: Date; // Fiscal date

  @CreateDateColumn()
  createdAt!: Date;
}